### PR TITLE
Delete values.xml

### PR DESCRIPTION
**Pull request by javiergamarra**
This should be specified in the child app and hardcoding the value can cause problems

### CODE REVIEW

**Comment by javiergamarra** [comment]
Can you review this PR? It's causing us problems with the latest phones :)

**Comment by brunofarache** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by brunofarache** [comment]
Thank you, pull request merged! <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by brunofarache** [comment]
@nhpatt  Released 1.0.8

**Comment by javiergamarra** [comment]
THX :D

**Pull request merged**
